name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Crate
      uses: actions/checkout@v4
    - name: Setup Toolchain
      uses: ./.github/actions/setup
    - name: Cache dependencies
      uses: ./.github/actions/cache
    - name: Run check
      run: cargo check
    - name: Run rustfmt
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy -- -D warnings
