name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Crate
      uses: actions/checkout@v4
    - name: Setup Toolchain
      uses: ./.github/actions/setup
    - name: Cache dependencies
      uses: ./.github/actions/cache
    - name: Run test
      run: cargo test --verbose
